export const WeatherIcons = {
  '01d': 'fas fa-sun', // Clear sky (day)
  '01n': 'fas fa-moon', // Clear sky (night)
  '02d': 'fas fa-cloud-sun', // Few clouds (day)
  '02n': 'fas fa-cloud-moon', // Few clouds (night)
  '03d': 'fas fa-cloud', // Scattered clouds (day)
  '03n': 'fas fa-cloud', // Scattered clouds (night)
  '04d': 'fas fa-cloud', // Broken clouds (day)
  '04n': 'fas fa-cloud', // Broken clouds (night)
  '09d': 'fas fa-cloud-showers-heavy', // Showers (day)
  '09n': 'fas fa-cloud-showers-heavy', // Showers (night)
  '10d': 'fas fa-cloud-sun-rain', // Rain (day)
  '10n': 'fas fa-cloud-moon-rain', // Rain (night)
  '11d': 'fas fa-bolt', // Thunderstorm (day)
  '11n': 'fas fa-bolt', // Thunderstorm (night)
  '13d': 'fas fa-snowflake', // Snow (day)
  '13n': 'fas fa-snowflake', // Snow (night)
  '50d': 'fas fa-smog', // Mist (day)
  '50n': 'fas fa-smog', // Mist (night)
};
